# Generated by Django 3.0.3 on 2020-03-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Save_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('road_address', models.CharField(max_length=500)),
                ('jibun_address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=13)),
                ('category', models.CharField(max_length=3)),
                ('writer', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
